
 const products = [
  {
    id: 1,
    title: 'Black baseball cap',
    category: 'Hats & Beanie',
    price: 12,
    image: 'https://storage.googleapis.com/a1aa/image/95514d06-5f74-46d5-af8c-27ce876abe11.jpg',
    bg: '',
    badge: null,
    description: `This stylish black baseball cap is perfect for everyday wear. ...`,
    sizeAndFit: `One size fits all. ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 2,
    title: 'Iridescent iPhone case',
    category: 'iPhone Cases',
    price: 19,
    image: 'https://storage.googleapis.com/a1aa/image/f0e9b45e-4c01-42bc-efb5-d5728ce3865a.jpg',
    bg: '',
    badge: 'New',
    description: `This iridescent phone case ...`,
    sizeAndFit: `Universal fit ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 3,
    title: 'Black analogue watch',
    category: 'Accessories',
    price: 43,
    image: 'https://storage.googleapis.com/a1aa/image/c941ca74-026c-4b01-76b5-d6441955ad0e.jpg',
    bg: '',
    badge: null,
    description: `Elegant black analogue watch ...`,
    sizeAndFit: `Adjustable strap ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 4,
    title: 'Ombré vinyl backpack',
    category: 'Purses',
    price: 29,
    image: 'https://storage.googleapis.com/a1aa/image/948030d8-a4dc-40c3-b9c5-f309f5d64004.jpg',
    bg: '',
    originalPrice: 37,
    badge: '-22%',
    description: `Trendy ombré vinyl backpack ...`,
    sizeAndFit: `Fits up to 15" laptops ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 5,
    title: 'Golden earrings',
    category: 'Accessories',
    price: 25,
    image: 'https://ld-wt73.template-help.com/intense/intense2/images/products/product-11-290x372.jpg',
    bg: '',
    badge: null,
    description: `Elegant golden earrings ...`,
    sizeAndFit: `One size ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 6,
    title: 'Iridescent tote bag',
    category: 'Purses',
    price: 32,
    image: 'https://ld-wt73.template-help.com/intense/intense2/images/products/product-04-290x372.jpg',
    bg: '',
    badge: 'New',
    description: `Shiny and stylish tote bag ...`,
    sizeAndFit: `Size: 15" x 13" ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 7,
    title: 'Stationery collection',
    category: 'Stationery',
    price: 25,
    image: 'https://ld-wt73.template-help.com/intense/intense2/images/products/product-05-290x372.jpg',
    bg: '',
    originalPrice: 45,
    badge: '-33%',
    description: `Complete stationery collection ...`,
    sizeAndFit: `Box size: 10" x 8" ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 8,
    title: 'Iridescent belt bag',
    category: 'Purses',
    price: 10,
    image: 'https://ld-wt73.template-help.com/intense/intense2/images/products/product-06-290x372.jpg',
    bg: '',
    badge: null,
    description: `Trendy iridescent belt bag ...`,
    sizeAndFit: `Fits waist sizes ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 9,
    title: 'White sneakers',
    category: 'Accessories',
    price: 40,
    image: 'https://ld-wt73.template-help.com/intense/intense2/images/products/product-12-290x372.jpg',
    bg: '',
    badge: null,
    description: `Classic white sneakers ...`,
    sizeAndFit: `Available in sizes ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 10,
    title: 'Travel backpack',
    category: 'Purses',
    price: 60,
    image: 'https://th.bing.com/th/id/OIP.J9CgrEcGL6y6nHfJRqrJlQHaHa?cb=iwp2&rs=1&pid=ImgDetMain',
    bg: '',
    originalPrice: 80,
    badge: '-25%',
    description: `Rugged travel backpack ...`,
    sizeAndFit: `Dimensions: 18" x 12" x 7" ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 11,
    title: 'Phone case with chain',
    category: 'iPhone Cases',
    price: 45,
    image: 'https://ld-wt73.template-help.com/intense/intense2/images/products/product-08-290x372.jpg',
    bg: '',
    originalPrice: 53,
    badge: null,
    description: `Elegant phone case with stylish detachable chain ...`,
    sizeAndFit: `Universal fit ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
  {
    id: 12,
    title: 'Rose eau de toilette',
    category: 'Eau de Toilette',
    price: 55,
    image: 'https://ld-wt73.template-help.com/intense/intense2/images/products/product-09-290x372.jpg',
    bg: '',
    badge: 'New',
    description: `Charming rose fragrance ...`,
    sizeAndFit: `50ml bottle ...`,
    shippingAndReturns: `Free worldwide shipping ...`,
    reviews: `Customer reviews will be displayed here.`,
  },
];

export default products ;